# Generated by Django 3.2.24 on 2024-02-14 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0004_auto_20240214_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='apacheerrorlogs',
            name='log_level',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
