# Generated by Django 3.2.24 on 2024-02-14 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0005_apacheerrorlogs_log_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='apacheaccesslogs',
            name='log_level',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apacheattacklogs',
            name='log_level',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='log_level',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mysqllogs',
            name='log_level',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mysqlshutdownlogs',
            name='log_level',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mysqlstartuplogs',
            name='log_level',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nginxaccesslogs',
            name='log_level',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nginxerrorlogs',
            name='log_level',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nginxlogs',
            name='log_level',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
