# Generated by Django 3.2.24 on 2024-02-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0006_auto_20240214_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysqlstartuplogs',
            old_name='msu_created_at',
            new_name='created_at',
        ),
    ]
